# Site settings
title: 快看！！有飞机！！！
email: yingxuetan@163.com
description: > # this means to ignore newlines until "baseurl:"
  快看！！这里有飞机！！！
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.html5-css3.com" # the base hostname & protocol for your site
twitter_username: lujintan
github_username:  lujintan
github_site: https://github.com/lujintan
wx_username: kuaikan_youfeiji

# Build settings
markdown: kramdown
